### ISSUE TITLE
table的column在render渲染Poptip组件时Poptip会被遮住

### ISSUE THREAD

**Issue by SilenceDN** [iview/iview#121]
改Poptip的z-index也没用

**Comment by icarusion** [comment]
代码 截图

**Comment by SilenceDN** [comment]
![qq 20161213100811](https://cloud.githubusercontent.com/assets/16896067/21124838/363eec06-c11c-11e6-9018-2d65647e6862.png)

![qq 20161213100441](https://cloud.githubusercontent.com/assets/16896067/21124788/ef5e5222-c11b-11e6-9329-915fbac9bb42.png)

**Comment by icarusion** [comment]
fixed。
你可以先用覆盖样式的方法解决：
```css
.ivu-table-body{
    position: static !important;
}
```
