### ISSUE TITLE
Checkbox 如何设置图标大小啊

### ISSUE THREAD

**Issue by QinFeiFei** [iview/iview#1302]
Checkbox 如何设置图标大小啊

**Comment by ihuguowei** [comment]
覆盖如下样式
```css
.ivu-checkbox-inner {
    width: your_width;
    height: your_height;
}
```
另外不建议在 issue中询问如何使用之类的问题。
