### ISSUE TITLE
Tooltip 在处理长段文字时候，溢出文本被隐藏

### ISSUE THREAD

**Issue by ihuguowei** [iview/iview#1723]
RT： 具体表现如下图所示
![image](https://user-images.githubusercontent.com/3097742/29812345-d24e1788-8cd8-11e7-85eb-f1d2786037c8.png)

我定位到是样式问题
``` css
.ivu-tooltip-inner {
    max-width: 250px;
    min-height: 34px;
    padding: 8px 12px;
    color: #fff;
    text-align: left;
    text-decoration: none;
    background-color: rgba(70,76,91,.9);
    border-radius: 4px;
    box-shadow: 0 1px 6px rgba(0,0,0,.2);
    white-space: nowrap;
}
```
其中`white-space: nowrap;`会导致该问题，去除即可，副作用未发现。
