### ISSUE TITLE
small Input icon position incorrectly in FormItem

### ISSUE THREAD

**Issue by chavyleung** [iview/iview#2149]
Input size="small" icon="ios-search" 
如果放在FormItem内，Icon会错位

```html
    <Form inline>
      <FormItem>
        <Input placeholder="input here" icon="ios-search" style="width:300px" size="small"></Input>
      </FormItem>
    </Form>
```

重现地址：https://codepen.io/chavyleung/pen/ZXPQYQ

**Comment by chavyleung** [comment]
临时解决：
```css 
.ivu-form-item .ivu-input-wrapper-small .ivu-input-icon {
    line-height: 32px;
}
```
