### ISSUE TITLE
Problem : 自定义官方组件样式 CSS 不生效

### ISSUE THREAD

**Issue by Tonysmark** [iview/iview#5533]
最近使用输入框的时候想加一点阴影效果, 然后我本以为就像其他组件一样直接定义css样式就可以了
``` css
  .ivu-input {
    text-align: center;
    box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14),
      0 3px 1px -2px rgba(0, 0, 0, 0.12), 0 1px 5px 0 rgba(0, 0, 0, 0.2);
  }
```
![HMZYA3XQ)UK$9)V B@UM`V](https://user-images.githubusercontent.com/22767695/55287880-9986b500-53e1-11e9-9c4a-6fffb087f1dd.png)
但是我什么也没得到 就好像我没写一样,但是如果我把样式写在`app.vue`中 就立刻生效了,这样的情况请重视!!!
