### ISSUE TITLE
[Bug Report]Custom some component style coulden't work fine.

### ISSUE THREAD

**Issue by Tonysmark** [iview/iview#5534]
### Environment
windows 10(1809) / electron 4.0.0 / vue 2.6.6

### Reproduction link
[https://jsfiddle.net/0cyuLhg8/2/#&togetherjs=fuBT0ARSaU](https://jsfiddle.net/0cyuLhg8/2/#&togetherjs=fuBT0ARSaU)

### Steps to reproduce
on the `search_tpl.vue` file
``` vue
<template>
  <div class="container">
    <div class="input">
      <Input search v-model="value" placeholder="search" size="large"/>
    </div>
    <img src="../assets/pleaceholder.png" alt>
  </div>
</template>
<script>
export default {
  data() {
    return {
      value: ""
    };
  }
};
</script>
<style lang="less" scoped>
.container {
  padding: 15px 0;
  .input {
    margin: 0 auto 1rem auto;
    width: 500px;
    .ivu-input{
      text-align: center;
      box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14),
        0 3px 1px -2px rgba(0, 0, 0, 0.12), 0 1px 5px 0 rgba(0, 0, 0, 0.2);
    }
  }
}
</style>

```
This component won't work unless I put this into `app.vue` file 
``` css 
.ivu-input{
      text-align: center;
      box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14),
        0 3px 1px -2px rgba(0, 0, 0, 0.12), 0 1px 5px 0 rgba(0, 0, 0, 0.2);
    }
```

### What is expected?
Only this component should have the style that I wrote

### What is actually happening?
Just won't work
