### ISSUE TITLE
[Bug Report]在table标签中使用checkbox组件，当table中cellspacing属性未设置，或不设置为0时，checkbox图标会出现诡异的问题，特别是设置indeterminate属性后

### ISSUE THREAD

**Issue by silencyXiao** [iview/iview#5741]
### Environment
window10/chrome/vue 2.6 

### Reproduction link
[https://run.iviewui.com/UZ9Pktqh](https://run.iviewui.com/UZ9Pktqh)

### Steps to reproduce
直接看demo

### What is expected?
问题比较诡异，希望有时间可以解决，我也是在写demo的时候，无意中找到问题是由于table中cellspacing属性产生的

### What is actually happening?
希望能修复该问题

**Comment by CarterLi** [comment]
```css
.ivu-checkbox-inner::after {
  display: block !important;
}
```

workaround，不知道会不会引发其他问题
