### ISSUE TITLE
[Bug Report]Poptip组件与Table 组件冲突，导致 Poptip confirm 图标(icon)位置不正确。

### ISSUE THREAD

**Issue by FantasyLeo** [iview/iview#6096]
### Environment
window10/ Version 75.0.3770.142 (Official Build) (64-bit) / vue2.6.x

### Reproduction link
[https://run.iviewui.com/pl9f8QBe](https://run.iviewui.com/pl9f8QBe)

### Steps to reproduce
在重现链接中，点击 删除按钮。弹出的Poptip样式有问题。icon的位置正确

### What is expected?
icon 在文字的左端

### What is actually happening?
icon 与文字重叠，且居中

**Comment by FantasyLeo** [comment]
参考图片
![Snipaste_2019-07-23_13-54-03](https://user-images.githubusercontent.com/5919322/61686661-db51b780-ad52-11e9-9449-93021289dc31.png)
![Snipaste_2019-07-23_13-54-18](https://user-images.githubusercontent.com/5919322/61686663-dd1b7b00-ad52-11e9-8319-b8b3bf1c51d5.png)

**Comment by FantasyLeo** [comment]
```javascript
 // table columns 
{
      title: 'Action',
      slot: 'action',
      width: 150,
      align: 'center' // 与该值冲突
}
```

**Comment by FantasyLeo** [comment]
临时解决方法：
在Poptip上添加样式
`text-align: left;`

**Comment by FantasyLeo** [comment]
【延伸】
```css
.ivu-table-wrapper {
    position: relative;
    border: 1px solid #dcdee2;
    border-bottom: 0;
    border-right: 0;
    overflow: hidden;  // 这个overflow 有必要吗？还会导致Poptip被遮挡。ant.design组件中并没有该项。这一项有明确目的吗？在身情况下会起到作用？去掉该项后，项目中暂时没发现问题。
}
```

**Comment by FantasyLeo** [comment]
> 【延伸】
> 
> ```css
> .ivu-table-wrapper {
>     position: relative;
>     border: 1px solid #dcdee2;
>     border-bottom: 0;
>     border-right: 0;
>     overflow: hidden;  // 这个overflow 有必要吗？还会导致Poptip被遮挡。ant.design组件中并没有该项。这一项有明确目的吗？在身情况下会起到作用？去掉该项后，项目中暂时没发现问题。
> }
> ```


```less
    &-wrapper{
        position: relative;
        border: 1px solid @border-color-base;
        border-bottom: 0;
        border-right: 0;
        overflow: hidden; // 开启 max-height 时，没有 overflow: hidden，则底部多出 1px，早期没有 overflow 是因为有些控件没有加 transfer
    }
```
哦？
