### ISSUE TITLE
[Bug Report]The Page component is used in the Dropdown component. Dropdown is triggered by the click method. If there is a click on the front 5 pages of the Page component or 5 pages backward, the drop-down content is retracted.

### ISSUE THREAD

**Issue by helloprogh** [iview/iview#6184]
### Environment
windowns10/chrome/vue2.x

### Reproduction link
[https://run.iviewui.com/1d3NvtwV](https://run.iviewui.com/1d3NvtwV)

### Steps to reproduce
1. The Page component is used in the Dropdown component, and Dropdown uses the click method to trigger
2. Click on the front 5 pages or the back 5 pages of the page component, and the drop-down content is retrieved.

### What is expected?
The current page number of the paging component changes, and the drop-down content continues to display.

### What is actually happening?
The current page number of the paging component changes, and the drop-down content is recovered.

---
Use the table to display a list of messages in the drop-down, you need to use the paging component

**Comment by helloprogh** [comment]
The cause of the problem is that after clicking the first 5 pages, the element that triggered the click event disappears.This triggers a callback function registered on the Dropdown component using the v-clickoutside directive.A temporary solution that uses the css pseudo-element overlay icon to make the element that triggered the click event a li element instead of an icon that will disappear. It has been practiced that this is effective.Css code is as follows：
```css
  .ivu-page-item-jump-next, .ivu-page-item-jump-prev {
     position: relative;
  }
  .ivu-page-item-jump-next::before, .ivu-page-item-jump-prev::before {
    content: '';
    position: absolute;
    top: 0px;
    left: 0px;
    width: 100%;
    height: 100%;
  }
```
## Reproduction link

https://run.iviewui.com/6NTN3eYR
