### ISSUE TITLE
modal窗口垂直居中显示

### ISSUE THREAD

**Issue by gxlmyacc** [iview/iview#70]
你好，我参照[https://www.iviewui.com/components/modal](url)的说明实现一个垂直居中的modal浮层，但是不知作用，而且导致ivu-modal-conent元素没有显示，是不是iview后来改过什么导致这种方式不支持了?

**Comment by icarusion** [comment]
样式被覆盖了，临时解决办法：
```css
<style lang="less">
    .vertical-center-modal{
        display: flex;
        align-items: center;
        justify-content: center;

        &.ivu-modal-hidden{
            display: none;
        }
        .ivu-modal{
            top: 0;
        }
    }
</style>
```
